### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by RahulSundar** [Griffin98/Segmentation_based_Semantic_Matting#1]

**Comment by RahulSundar** [comment]
Hi!
What are the package dependencies to run the code?
Thanks
Rahul Sundar

**Comment by Griffin98** [comment]
My VirtualEnv looks likes this. My packages are old however newer packages should work fine too.

tensorflow==1.13.1
imgaug==0.3.0
matplotlib==2.2.3
numpy==1.16.3
h5py==2.9.0
torchsummary==1.5.1
scikit_image==0.16.1
torchvision==0.4.1
torch==1.3.0
opencv_python_headless==4.1.1.26
scipy==1.2.1
Keras==2.2.4
ipython==7.11.0
Pillow==6.2.1
skimage==0.0
